name = "Docsy"
license = "Apache 2.0"
licenselink = "https://github.com/google/docsy/blob/master/LICENSE"
description = "A Hugo theme for technical documentation sites"
homepage = "https://docsy.dev"
tags = ["documentation", "multilingual", "customizable", "responsive", "docs"]
features = []
min_version = 0.53

[author]
  name = "The Docsy Authors"
  homepage = "https://docsy.dev"
