destination: _site
markdown: kramdown
kramdown:
  syntax_highlighter: rouge
  toc_levels: "2,3"
highlighter: rouge
paginate: 5
paginate_path: "/blog/page:num/"
plugins:
  - jekyll-paginate
  - jekyll-autoprefixer
  - jekyll-inline-svg
  - jekyll-relative-links
  - jekyll-feed
  - jekyll-sitemap
site_url: https://gvisor.dev
feed:
  path: blog/index.xml
svg:
  optimize: true
defaults:
  - scope:
      path: ""
    values:
      layout: default
analytics: "UA-150193582-1"
authors:
  lucasmanning:
    name: Lucas Manning
    email: lucasmanning@google.com
    url: https://twitter.com/lucassmanning
  jsprad:
    name: Jeremiah Spradlin
    email: jsprad@google.com
  zkoopmans:
    name: Zach Koopmans
    email: zkoopmans@google.com
  igudger:
    name: Ian Gudger
    email: igudger@google.com
  fvoznika:
    name: Fabricio Voznika
    email: fvoznika@google.com
  ianlewis:
    name: Ian Lewis
    email: ianlewis@google.com
    url: https://twitter.com/IanMLewis
  mpratt:
    name: Michael Pratt
    email: mpratt@google.com
  nybidari:
    name: Nayana Bidari
    email: nybidari@google.com
  jianfengt:
    name: Jianfeng Tan
    email: henry.tjf@antgroup.com
  yonghe:
    name: Yong He
    email: chenglang.hy@antgroup.com
